# Explore with pandas dataframes

In [1]:
import sys
sys.path.append("../python/")
import pentoref.IO as IO

In [8]:
# Get the dataframes (can also use a database method instead)
CORPUS = "TAKE"  # Change this to one of [TAKE, TAKECV, PENTOCV] (as of 2020.05.22, PENTOCV takes 3-4 mins)
dfwords, dfutts, dfrefs, dfscenes, dfactions = IO.convert_subcorpus_raw_data_to_dataframes("../../../pentoref/{0}_PENTOREF".format(CORPUS))

Extracting TAKE
TAKE
extracting files in textgrid format
7 Transcription files read.
/Users/julian/git/pentoref/TAKE_PENTOREF/derived_data/multimodal_data/scene_information/r1
/Users/julian/git/pentoref/TAKE_PENTOREF/derived_data/multimodal_data/scene_information/r2
/Users/julian/git/pentoref/TAKE_PENTOREF/derived_data/multimodal_data/scene_information/r3
/Users/julian/git/pentoref/TAKE_PENTOREF/derived_data/multimodal_data/scene_information/r4
/Users/julian/git/pentoref/TAKE_PENTOREF/derived_data/multimodal_data/scene_information/r5
/Users/julian/git/pentoref/TAKE_PENTOREF/derived_data/multimodal_data/scene_information/r6
/Users/julian/git/pentoref/TAKE_PENTOREF/derived_data/multimodal_data/scene_information/r7
1137 text files read. 1146 XML files parsed.
Processing:
r7...
r1...
r6...
r3...
r4...
r5...
r2...
Done.
8605 words
2597 utterances
1035 references
15585 scenes
no actions

In [10]:
dfwords

          word    starttime      endtime gameID  refID  uttID  position
0       rechts   139.444126   139.827419   r7_1      1      1         1
1        unten   139.827419   140.170477   r7_1      1      1         2
2         okay   143.593969   144.005850   r7_1      1      2         1
3        links   150.785674   151.034497   r7_2      2      3         1
4         oben   151.034497   151.232497   r7_2      2      3         2
...        ...          ...          ...    ...    ...    ...       ...
8600       ein  2941.726608  2942.035883  r2_80   1034    193         2
8601    grader  2942.035883  2942.736678  r2_80   1034    193         3
8602    Strich  2942.736678  2943.392483  r2_80   1034    193         4
8603  hellblau  2944.302921  2945.037000  r2_80   1034    193         5
8604        ja  2948.411011  2948.564671  r2_80   1034    194         1

[8605 rows x 7 columns]

In [4]:
dfwords

           word   lemma  tag    gameID  uttID  position
0          okay    Okay  NNP  r7_1_1_s      2         1
1          dann    dann   RB  r7_1_1_s      4         1
2         nehme  nehmen   VB  r7_1_1_s      4         2
3           ich     ich  PRP  r7_1_1_s      4         3
4        einmal  einmal   RB  r7_1_1_s      4         4
...         ...     ...  ...       ...    ...       ...
32627     nicht   nicht   RB  r2_2_9_b  13897         4
32628     genug   genug   IN  r2_2_9_b  13897         5
32629    Drogen  Drogen   NN  r2_2_9_b  13897         6
32630       fÃ¼r     fÃ¼r   RB  r2_2_9_b  13897         7
32631  genommen  nehmen  VBN  r2_2_9_b  13897         8

[32632 rows x 6 columns]

In [5]:
dfrefs

,refID,uttID,gameID,text,id,piece,location
0,1,4,r7_1_1_s,das Blaue,I,target,None
1,2,6,r7_1_1_s,das rote Kreuz,X,target,None
2,3,13,r7_1_2_s,das Braune,Y,target,None
3,4,13,r7_1_2_s,GrÃ¼ne,W,target,None
4,5,13,r7_1_2_s,das Pinke,P,target,None
...,...,...,...,...,...,...,...
2748,2749,13841,r2_2_8_s,"die <v=""orange"">orangene</v> Eins",L,target,None
2749,2750,13861,r2_2_9_s,das grÃ¼ne $T,T,target,None
2750,2751,13861,r2_2_9_s,das Plus,X,target,None
2751,2752,13861,r2_2_9_s,die braune Eins,Y,target,None
2752,2753,13893,r2_2_9_b,$S,Z,target,None

In [6]:
dfscenes

,timestampID,pieceID,isLandmark,isTarget,position_global,position_x,position_y,shape,shape_distribution,shape_orientation,shape_skewness_horizontal,shape_skewness_vertical,shape_edges,colour,colour_distribution,colour_hsv,colour_rgb,gameID
0,1000.070485,0,None,None,right center,411,230,Z,"F:6.89053387935e-40,I:4.83548786325e-76,L:7.86...",11.6014718023,symmetric,top-skewed,8,Blue,"Blue:0.999700621707,Brown:0.000296425744653,Gr...","H:98.6112454655,S:247.136638452,V:124.339782346","B:124.07859734,G:89.676541717,R:6.24425634825",r7_1_8_b
1,1000.070485,1,None,None,left center,96,211,N,"F:2.12573638167e-11,I:6.42386426769e-10,L:0.22...",-31.3615215062,symmetric,top-skewed,6,Orange,"Blue:9.34501375828e-69,Brown:0.306709194149,Gr...","H:15.9634551495,S:204.57751938,V:148.975083056","B:33.6633444075,G:93.792358804,R:147.1910299",r7_1_8_b
2,1000.070485,2,None,None,right center,475,251,I,"F:3.31219772628e-32,I:0.8026648015,L:7.4862670...",11.0710205311,right-skewed,symmetric,5,Blue,"Blue:0.999924220384,Brown:2.80053821679e-05,Gr...","H:104.832386364,S:253.080255682,V:129.713068182","B:129.015625,G:66.5561079545,R:3.16193181818",r7_1_8_b
3,1000.070485,3,None,None,center top,371,89,T,"F:0.0197491515464,I:0.0,L:9.41905134036e-55,N:...",-4.89481960415,symmetric,top-skewed,8,Blue,"Blue:0.64692034686,Brown:1.71923570471e-07,Gre...","H:77.8064304462,S:104.601706037,V:107.101049869","B:90.0052493438,G:106.650262467,R:63.188976378",r7_1_8_b
4,1000.070485,4,None,None,left center,189,260,N,"F:1.19677161322e-08,I:3.10492978271e-06,L:0.02...",1.07625283992,symmetric,bottom-skewed,10,Green,"Blue:7.72594566064e-13,Brown:0.000487012808913...","H:46.5682989691,S:126.580541237,V:121.092139175","B:62.3885309278,G:119.995489691,R:88.3801546392",r7_1_8_b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462751,999.523810,7,None,None,left center,111,217,T,"F:0.113214929292,I:0.0,L:7.73243939574e-10,N:0...",-30.4409173878,right-skewed,bottom-skewed,8,Green,"Blue:0.250180171399,Brown:1.66838314902e-06,Gr...","H:75.8621633957,S:111.285714286,V:122.777727065","B:99.0666362392,G:122.613874943,R:69.9119123688",r2_1_5_b
462752,999.523810,8,None,None,right center,470,221,U,"F:0.00500157235342,I:0.0,L:1.28968412212e-66,N...",-4.63037287782,right-skewed,top-skewed,8,Yellow,"Blue:1.63718633875e-40,Brown:0.0054061757458,G...","H:29.4419452888,S:144.559270517,V:166.300911854","B:73.7866261398,G:162.880851064,R:164.669300912",r2_1_5_b
462753,999.523810,9,None,None,center top,160,154,Z,"F:4.49819622507e-06,I:0.0,L:3.53605938125e-17,...",2.86935279314,right-skewed,symmetric,8,Blue,"Blue:0.999730004065,Brown:0.000248021984938,Gr...","H:98.6258278146,S:184.086092715,V:161.092715232","B:160.496215705,G:127.46641438,R:46.775307474",r2_1_5_b
462754,999.523810,10,None,None,center top,229,204,L,"F:0.147479857218,I:3.91845514451e-29,L:0.84281...",30.2893961756,right-skewed,bottom-skewed,6,Orange,"Blue:8.85179130959e-51,Brown:0.0310922086991,G...","H:17.8257804632,S:195.941087613,V:184.744712991","B:46.1525679758,G:127.372608258,R:183.058408862",r2_1_5_b
462755,999.523810,11,None,None,right center,497,281,F,"F:0.660145034167,I:2.37909083135e-13,L:1.06245...",41.8778312258,right-skewed,top-skewed,6,Blue,"Blue:0.999763984463,Brown:0.000222312114565,Gr...","H:100.365079365,S:191.125448029,V:162.286226318","B:162.092165899,G:120.52124936,R:42.1607782898",r2_1_5_b

In [7]:
dfactions

       starttime   endtime hand           action piece    gameID
0        230.522   230.787   lh    move_to_piece     I  r7_1_2_b
1        230.787   230.892   lh       grab_piece     I  r7_1_2_b
2        230.892   231.950   lh  move_with_piece     I  r7_1_2_b
3        231.950   232.055   lh       drop_piece     I  r7_1_2_b
4        232.055   232.320   lh          retract     I  r7_1_2_b
...          ...       ...  ...              ...   ...       ...
12051   1799.358  1799.930   rh  move_with_piece     Z  r2_2_9_b
12052   1799.930  1801.025   rh     rotate_piece     Z  r2_2_9_b
12053   1801.025  1803.072   rh  move_with_piece     Z  r2_2_9_b
12054   1803.072  1803.310   rh       drop_piece     Z  r2_2_9_b
12055   1803.310  1804.215   rh          retract     Z  r2_2_9_b

[12056 rows x 6 columns]